

-- Delete job
EXEC jobs.sp_delete_job @job_name='AgentJob_Goal_DeltaLoad'
GO

EXEC jobs.sp_add_job @job_name='AgentJob_Goal_DeltaLoad'
GO
-- Add job step for updating table with new or changed rows
EXEC jobs.sp_add_jobstep @job_name='AgentJob_Goal_DeltaLoad',
@command=N'
INSERT INTO goal_archive
SELECT 
 [Id]
      ,[SinkCreatedOn]
      ,[SinkModifiedOn]
      ,[statecode]
      ,[statuscode]
      ,[fiscalperiod]
      ,[amountdatatype]
      ,[fiscalyear]
      ,[consideronlygoalownersrecords]
      ,[isfiscalperiodgoal]
      ,[isoverride]
      ,[rolluponlyfromchildgoals]
      ,[isoverridden]
      ,[isamount]
      ,[rollupqueryinprogressintegerid]
      ,[rollupqueryinprogressintegerid_entitytype]
      ,[parentgoalid]
      ,[parentgoalid_entitytype]
      ,[rollupqueryactualdecimalid]
      ,[rollupqueryactualdecimalid_entitytype]
      ,[goalwitherrorid]
      ,[goalwitherrorid_entitytype]
      ,[modifiedonbehalfby]
      ,[modifiedonbehalfby_entitytype]
      ,[rollupquerycustommoneyid]
      ,[rollupquerycustommoneyid_entitytype]
      ,[rollupquerycustomdecimalid]
      ,[rollupquerycustomdecimalid_entitytype]
      ,[metricid]
      ,[metricid_entitytype]
      ,[goalownerid]
      ,[goalownerid_entitytype]
      ,[rollupqueryactualintegerid]
      ,[rollupqueryactualintegerid_entitytype]
      ,[createdby]
      ,[createdby_entitytype]
      ,[rollupquerycustomintegerid]
      ,[rollupquerycustomintegerid_entitytype]
      ,[transactioncurrencyid]
      ,[transactioncurrencyid_entitytype]
      ,[owningteam]
      ,[owningteam_entitytype]
      ,[createdonbehalfby]
      ,[createdonbehalfby_entitytype]
      ,[modifiedby]
      ,[modifiedby_entitytype]
      ,[rollupqueryactualmoneyid]
      ,[rollupqueryactualmoneyid_entitytype]
      ,[owninguser]
      ,[owninguser_entitytype]
      ,[owningbusinessunit]
      ,[owningbusinessunit_entitytype]
      ,[rollupqueryinprogressmoneyid]
      ,[rollupqueryinprogressmoneyid_entitytype]
      ,[rollupqueryinprogressdecimalid]
      ,[rollupqueryinprogressdecimalid_entitytype]
      ,[ownerid]
      ,[ownerid_entitytype]
      ,[customrollupfieldmoney_base]
      ,[inprogressmoney_base]
      ,[actualmoney_base]
      ,[actualmoney]
      ,[computedtargetasoftodaymoney]
      ,[stretchtargetmoney_base]
      ,[targetmoney_base]
      ,[customrollupfieldmoney]
      ,[inprogressmoney]
      ,[stretchtargetmoney]
      ,[computedtargetasoftodaymoney_base]
      ,[targetmoney]
      ,[title]
      ,[targetstring]
      ,[entityimage_timestamp]
      ,[createdon]
      ,[modifiedonbehalfbyyominame]
      ,[percentage]
      ,[rollupqueryinprogressintegeridname]
      ,[actualinteger]
      ,[owneridtype]
      ,[treeid]
      ,[depth]
      ,[stretchtargetinteger]
      ,[modifiedbyname]
      ,[rollupqueryinprogressmoneyidname]
      ,[lastrolledupdate]
      ,[rollupqueryinprogressdecimalidname]
      ,[parentgoalidname]
      ,[goalowneridtype]
      ,[overriddencreatedon]
      ,[rollupquerycustommoneyidname]
      ,[rollupqueryactualintegeridname]
      ,[createdonbehalfbyyominame]
      ,[exchangerate]
      ,[customrollupfielddecimal]
      ,[computedtargetasoftodayinteger]
      ,[goalwitherroridname]
      ,[goalowneridname]
      ,[goalowneridyominame]
      ,[timezoneruleversionnumber]
      ,[targetdecimal]
      ,[rollupquerycustomdecimalidname]
      ,[customrollupfieldstring]
      ,[actualstring]
      ,[versionnumber]
      ,[stretchtargetdecimal]
      ,[metricidname]
      ,[goalid]
      ,[utcconversiontimezonecode]
      ,[rollupqueryactualdecimalidname]
      ,[rolluperrorcode]
      ,[modifiedon]
      ,[importsequencenumber]
      ,[owneridyominame]
      ,[computedtargetasoftodaydecimal]
      ,[entityimageid]
      ,[createdbyname]
      ,[inprogressdecimal]
      ,[createdonbehalfbyname]
      ,[rollupquerycustomintegeridname]
      ,[goalstartdate]
      ,[inprogressinteger]
      ,[rollupqueryactualmoneyidname]
      ,[targetinteger]
      ,[actualdecimal]
      ,[transactioncurrencyidname]
      ,[goalenddate]
      ,[inprogressstring]
      ,[owneridname]
      ,[modifiedonbehalfbyname]
      ,[entityimage_url]
      ,[computedtargetasoftodaypercentageachieved]
      ,[stretchtargetstring]
      ,[customrollupfieldinteger]
	  , CAST(GETDATE() as date) [LoadDate]
FROM goal 
WHERE DATEDIFF(wk,getdate(),modifiedon) = 0
AND YEAR(modifiedon) = YEAR(GETDATE())
;',
@credential_name='job_execution',
@target_group_name='d365Group'

/* Schedule job execution*/	
EXEC jobs.sp_update_job
@job_name='AgentJob_Goal_DeltaLoad',
@enabled=1,
@schedule_interval_type='Weeks',
@schedule_interval_count=1,
@schedule_start_time = '20211002 20:00'

